baseURL = 'https://alanjeffares.github.io'
languageCode = 'en-us'
title = 'Alan Jeffares'
theme = "hugo-xmin"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[Params]
  description = "Alan Jeffares' personal homepage."
  footer = "[[twitter](https://twitter.com/Jeffaresalan)] | [[scholar](https://scholar.google.com/citations?user=e65kJ08AAAAJ&hl=en)] | [[github](https://github.com/alanjeffares)] | [[linkedin](https://linkedin.com/in/alanjeffares)]"
  
  
